GET http://localhost:3000/rentings

###

POST http://localhost:3000/rentings
content-type: application/json

{
    "vehicleId": "652452",
    "clientId": "652470",
    "beginDate": "20221231",
    "endDate": "20230102"
}

###
GET http://localhost:3000/rentings/633497df56c62d12e6ee46ca


###
PUT http://localhost:3000/rentings/633497df56c62d12e6ee46ca
content-type: application/json

{
    "endDate": "20220104"
}

###
DELETE http://localhost:3000/rentings/633497df56c62d12e6ee46ca

